apiVersion: v1
kind: service
metadata: 
    name: nginx-lb
spec:
    type: {{ .Values.service.type}}
    selector: 
      purpose: helm-demo
      project: roboshop
    ports:
        - protocal: TCP
            port: {{ .Values.service.serviceport }}
            targetPort: 80
            nodePort: 30007